name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: minddocdev/actions-ci-yarn@master
      - name: yarn install, build, and test
        run: |
          install
          build
          test:unit
        env:
          CI: true
